### PR TITLE
Fix for JSON storage in JournalEntry via moving data to JE flags / supports old data loading. 

### PR DESCRIPTION
**Pull request by typhonrt**
Alrighty... So this is a major improvement / bug fix. This PR fixes JSON storage in Journal entries through escaping then base64 encoding. On the flip side decoding from base64 and parsing to a JSON object. Two new utility methods were added around the process, `Utils.encodeJE` and `Utils.decodeJE`.  NPM module [jsesc](https://www.npmjs.com/package/jsesc) has been added to the utilities directory and is MIT licensed. It is necessary as base64 encoding / decoding needs to be in the latin1 character set and jsesc will escape the full range of unicode. The nice thing is that TinyMCE works fine w/ the escaped unicode!  

The nice thing about this fix is that it wholly opens up editing quests w/ TinyMCE allowing all sorts of rich content internally to FoundryVTT and dragging any source into TinyMCE based fields. 

I have done some reasonably thorough testing. 

If there is a downside being that this is a new storage format for quests everyone will have to start from scratch entering new quests and removing any existing old quest data. I don't see this as too much of a problem because FQL is gratuitously broken right now when it comes to this issue. 

-------

Embed tons of things! 

image

-------

The big problem this fixes is that when a JournalEntry was updated there was some weird substitution / incomplete escape going on... 

Where things happened...
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/blob/master/modules/entities/quest.mjs#L260

For instance all HTML escaped like 
`<a href=\"https://www.google.com\">link</a>`
becomes the following after the document update:
`<a href="\&quot;https://www.google.com\&quot;">link</a>`

Things will fail to parse at `<a href=` as an unescaped " occurs. Weird that the document update does this.

This is really weird because it is a JournalEntry update for the content field and if you trace it all the way into the document model the schema for the field is BLANK_STRING and while it has a clean function that is  `String(v).trim()`, so I don't think that explains the weird behavior.

Anyway... All fixed with this PR..

### CODE REVIEW

**Review by xdy — CHANGES_REQUESTED** [review]
Felt a bit harsh to throw away all old quests, so I took a look at converting any old quests on the fly. The following change worked on my game world.

I suggest changing lines 409-417 of quest.mjs to this:
```javascript
    try {
      content = Utils.decodeJE(entry.data.content);
      content.id = entry._id;
    } catch (e) {
      console.log(`${constants.moduleLabel} | Quest Folder contains invalid entry. Will try to read old quest format for "${entry.data.name}".`);
      try {
      let old = JSON.parse(entry.data.content);
	  let encoded = Utils.encodeJE(old);
	  content = Utils.decodeJE(encoded);
      content.id = entry._id;
	  console.log(`${constants.moduleLabel} | Quest Folder contained old quest format in "${entry.data.name}", will convert.`);
      } catch (e) {
        console.log(`${constants.moduleLabel} | Quest Folder contains invalid entry. The "${entry.data.name}" is either corrupted Quest Entry, or non-Quest Journal Entry.`);
        console.error(e);
      }
    }
```
or something like it. I.e. to try to convert any old quests to new quests.
Any defective quests will of course continue to be ignored and cause log lines until they are manually fixed/deleted.
I still think it's best to keep any broken quests so users can try to manually extract any data from the file.

**Comment by typhonrt** [comment]
> Works fine for me too, but it felt a bit harsh to throw away all old quests, so I took a look at converting any old quests on the fly. The following change worked on my game world.
> or something like it. I.e. to try to convert any old quests to new quests.
> Any defective quests will of course continue to be ignored and cause log lines until they are manually fixed/deleted.

Yeah I suppose that will work. I'm glad you submitted a solution as I don't have as much patience to act as a long term maintainer of FQL. Presently no quests are actually removed, so users would just continue to see console errors until they remove old quests. I think a migration guide clearly posted on the repo and in both Discord will be sufficient to resolve this matter.

I'll update the PR in the next day or so after a bit more testing.

**Comment by typhonrt** [comment]
Now I do want to comment about a potential security issue with the base64  encoding / decoding for JSON serialization in JournalEntry. Right now by default `CONFIG.TinyMCE` defines options for the toolbar displayed when editing. That allows one to directly edit the source code and is how I inserted the iframe w/ YouTube embedded video in the demo image above. 

The related FVTT issue to what happened on `0.7.10` and `0.8.x` regarding FQL breakage:
https://gitlab.com/foundrynet/foundryvtt/-/issues/5261

I'll be adding custom TinyMCE options soon to this PR to remove direct source code editing for security reasons, but enable as many other TinyMCE plugins possible to enable rich media input of data for FQL. 

So let this PR to percolate a bit before merge.

**Comment by typhonrt** [comment]
I have a few more commits coming in.. I'm investigating storing data in flags in the next commit and then adding a bit of security protection in filtering user data in a 4th commit.

**Comment by typhonrt** [comment]
So things should be good now. 
- moved data storage to flags
- provide custom TinyMCE toolbar removing source code editing / adding more media options
- fixed _id deprecated warning
- fixed handlebars template for {{{name}}} to {{name}} for task names preventing script execution.

**Comment by xdy** [comment]
Looks good, merging. Haven't tested all that well with old quests, will get back to that once the other PR:s are in.

**Comment by xdy** [comment]
Merged, but will hold off with the release for a while as @typhonrt said that more fixes were incoming.

**Comment by typhonrt** [comment]
I think I'll have something really good by Monday. Really bearing down and getting all the edge cases and everything that was present in FQL working and sailing smoothly w/ `0.8.x`. I'd like to get all the refactoring done before it get's hit by the masses. ;P If things go my way I'll have everything async and not a mixture of async / promises, so code readability for the next fellow is better.. Hah.. And add in some comments. Forein imparted some genius, but with that came an equal dose of madness.. ;)

**Comment by anthonyronda** [comment]
There's been a comment that all bug reports were closed 3-9 days ago, but the fixes are still forthcoming, which is putting the overall status of the project in question.

@typhonrt your time investment is super appreciated. Is there anything I can do to help tie up these loose ends today?

**Pull request merged**
