### PR TITLE
updated 0.7.7 ko.json

### PR DESCRIPTION
**Pull request by drdwing**
I'm sorry. This is the last fix. 😢

### CODE REVIEW

**Comment by typhonrt** [comment]
No worries. I appreciate the help for sure!

**Comment by typhonrt** [comment]
Hi @drdwing. I am reaching you through this last PR as I couldn't find you on Discord. I am making a v10 compatibility update for FQL by Monday next week. There are only two new language keys to translate for Korean. If you have the time to provide them that will be better than a machine translation. The keys are:

"BackgroundShow": "Click for regular background.",
"BackgroundUnshow": "Click for transparent background.",

I always appreciate your help with translations! 😄

**Comment by typhonrt** [comment]
Oh bother... I added some more keys surrounding data migration. Probably worth translating them as they show up in a chat message giving a synopsis of changes.  Thanks in advance!

```
      "ChatMessage": {
        "Footer": "You must manually update the above quests with valid document data from compendiums or your world.<br>",
        "Header": "Forien's Quest Log (DB migration)<br>Removed unlinked quest giver or reward items from the quests below:<p>",
        "Notification": "Forien's Quest Log - Removed unlinked quest giver or reward items from one or more quests. Please review the chat message for more info.",
        "QuestGiver": "Quest Giver",
        "QuestRewards": "Quest Rewards"
      },
```

**Comment by drdwing** [comment]
Hi. I haven't played D&D since Jan because my work was so hard. So I couldn't check Discord. Sorry!
I'll resume the game from next year, so it will be hard to check any update of the module. But I'll help you whenever you need Korean translation. 😊
 
"BackgroundShow": "클릭하여 배경을 표시",
"BackgroundUnshow": "클릭하여 배경을 투명화", 
 
Have a nice day!
 
-----Original Message-----

**Comment by drdwing** [comment]
My pleasure 😊      "ChatMessage": { "Footer": "위 퀘스트를 컴펜디움 또는 월드의 유효 문서 데이터로 수동으로 업데이트 해야 합니다.<br>", "Header": "Forien's Quest Log (DB 마이그레이션)<br>아래 퀘스트에서 연결되지 않은 퀘스트 제공자 또는 보상 아이템을 제거했습니다.<p>", "Notification": "Forien's Quest Log - 하나 이상의 연결되지 않은 퀘스트 제공자 또는 보상 아이템이 제거되었습니다. 자세한 내용은 채팅 메시지를 확인하십시오", "QuestGiver": "퀘스트 제공자", "QuestRewards": "퀘스트 보상" },
-----Original Message-----

**Pull request merged**
