### PR TITLE
Added Macros & Syntax section to README.md

### PR DESCRIPTION
**Pull request by jinh5**
I added a section about Macros & Syntax. Closes issue #69. The section provides examples of syntax for the user and briefly discusses the newly added macros.

### CODE REVIEW

**Comment by typhonrt** [comment]
Hi @jinh5. It's certainly a great idea to get the macro syntax made available. It might be better placed into the wiki. I just made a page for macro information in the wiki that I believe you can edit directly and add in this same content.

**Comment by jinh5** [comment]
> Hi @jinh5. It's certainly a great idea to get the macro syntax made available. It might be better placed into the wiki. I just made a [page for macro information](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/wiki/Macros) in the wiki that I believe you can edit directly and add in this same content.
> 
> Let me know if you have the ability to edit wiki pages.

**Comment by jinh5** [comment]
Hi @typhonrt, I don't have the ability to edit wiki pages.

**Comment by typhonrt** [comment]
Hi @jinh5. I believe you should have access now to edit the wiki.

**Comment by jinh5** [comment]
thanks!

**Comment by typhonrt** [comment]
I see that you successfully edited the wiki. Thanks! I'll close this PR now.

**Comment by jinh5** [comment]
@typhonrt  Since the wiki is updated could you close issue #69 as well?

**Comment by jinh5** [comment]
@typhonrt  Could we still include a section about the Macros in the readme? I was thinking about replacing the examples of the macros with a link to the wiki.

**Comment by typhonrt** [comment]
@jinh5 I have updated the README.

**Pull request closed without merging**
